default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: klynda
  password: 1234
  template: template0
  port: 5432

development:
  <<: *default
  database: java_tutor_admin_development

test:
  <<: *default
  database: java_tutor_admin_test

production:
  database: java_tutor_admin_production
  adapter:  postgresql
  pool:     5
  timeout: 5000