default: &default
  adapter:  postgresql
  pool:     5
  timeout: 5000

development:
  database: java_tutor_admin_development
  host:     localhost
  encoding: unicode
  username: klynda
  password: 123
  template: template0
  port: 5433
  <<: *default

test:
  database: java_tutor_admin_test
  host:     localhost
  encoding: unicode
  username: klynda
  password: 123
  template: template0
  port: 5433
  <<: *default

production:
  database: java_tutor_admin_production
  <<: *default
